package br.ufes.informatica.jurisproc.core.domain;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Relatoria extends PersistentObjectSupport implements Comparable<Relatoria>
{
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String juizMembro;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String voto;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private TurmaRecursal turmaRecursal;

	/** Getter for juizMembro. */
	public String getJuizMembro()
	{
		return juizMembro;
	}

	/** Setter for juizMembro. */
	public void setJuizMembro(String juizMembro)
	{
		this.juizMembro = juizMembro;
	}

	/** Getter for voto. */
	public String getVoto()
	{
		return voto;
	}

	/** Setter for voto. */
	public void setVoto(String voto)
	{
		this.voto = voto;
	}	

	public TurmaRecursal getTurmaRecursal()
	{
		return turmaRecursal;
	}

	public void setTurmaRecursal(TurmaRecursal turmaRecursal)
	{
		this.turmaRecursal = turmaRecursal;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Relatoria o)
	{
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}