package br.ufes.informatica.jurisproc.core.domain;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Relatoria extends PersistentObjectSupport implements Comparable<Relatoria> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String juizMembro;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String voto;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private TurmaRecursal Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private TurmaRecursal Target;
		
	




	/** Getter for juizMembro. */
	public String getJuizMembro() {
		return juizMembro;
	}
	
	/** Setter for juizMembro. */
	public void setJuizMembro(String juizMembro) {
		this.juizMembro = juizMembro;
	}

	/** Getter for voto. */
	public String getVoto() {
		return voto;
	}
	
	/** Setter for voto. */
	public void setVoto(String voto) {
		this.voto = voto;
	}




		
		/** Getter for Source. */
		public TurmaRecursal getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(TurmaRecursal Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Target. */
		public TurmaRecursal getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(TurmaRecursal Target) {
			this.Target = Target;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Relatoria o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}