package br.ufes.informatica.jurisproc.core.domain;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class SecaoJudiciaria extends PersistentObjectSupport implements Comparable<SecaoJudiciaria>
{
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */

	private String latitude;

	/** TODO: generated by FrameWeb. Should be documented. false */

	private String longitude;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private Integer secaoAdmissibilidade;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private TRF tribunalResponsavel;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToMany(mappedBy = "secaoJudiciaria", fetch = FetchType.EAGER)
	private Set<TurmaRecursal> turmasRecursais;

	/** Getter for nome. */
	public String getNome()
	{
		return nome;
	}

	/** Setter for nome. */
	public void setNome(String nome)
	{
		this.nome = nome;
	}

	/** Getter for latitude. */
	public String getLatitude()
	{
		return latitude;
	}

	/** Setter for latitude. */
	public void setLatitude(String latitude)
	{
		this.latitude = latitude;
	}

	/** Getter for longitude. */
	public String getLongitude()
	{
		return longitude;
	}

	/** Setter for longitude. */
	public void setLongitude(String longitude)
	{
		this.longitude = longitude;
	}

	/** Getter for secaoAdmissibilidade. */
	public Integer getSecaoAdmissibilidade()
	{
		return secaoAdmissibilidade;
	}

	/** Setter for secaoAdmissibilidade. */
	public void setSecaoAdmissibilidade(Integer secaoAdmissibilidade)
	{
		this.secaoAdmissibilidade = secaoAdmissibilidade;
	}

	/** Getter for tribunalResponsavel. */
	public TRF getTribunalResponsavel()
	{
		return tribunalResponsavel;
	}

	/** Setter for tribunalResponsavel. */
	public void setTribunalResponsavel(TRF tribunalResponsavel)
	{
		this.tribunalResponsavel = tribunalResponsavel;
	}	

	public Set<TurmaRecursal> getTurmasRecursais()
	{
		return turmasRecursais;
	}

	public void setTurmasRecursais(Set<TurmaRecursal> turmasRecursais)
	{
		this.turmasRecursais = turmasRecursais;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(SecaoJudiciaria o)
	{
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}