package br.ufes.informatica.jurisproc.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class SecaoJudiciaria extends PersistentObjectSupport implements Comparable<SecaoJudiciaria> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	  
	private String latitude;

	/** TODO: generated by FrameWeb. Should be documented. false */
	  
	private String longitude;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private Integer secaoAdmissibilidade;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private TRF tribunalResponsavel;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne(mappedBy="Target")
		private  Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Target")
		private Set<TurmaRecursal> Source;
		
	




	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for latitude. */
	public String getLatitude() {
		return latitude;
	}
	
	/** Setter for latitude. */
	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	/** Getter for longitude. */
	public String getLongitude() {
		return longitude;
	}
	
	/** Setter for longitude. */
	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	/** Getter for secaoAdmissibilidade. */
	public Integer getSecaoAdmissibilidade() {
		return secaoAdmissibilidade;
	}
	
	/** Setter for secaoAdmissibilidade. */
	public void setSecaoAdmissibilidade(Integer secaoAdmissibilidade) {
		this.secaoAdmissibilidade = secaoAdmissibilidade;
	}

	/** Getter for tribunalResponsavel. */
	public TRF getTribunalResponsavel() {
		return tribunalResponsavel;
	}
	
	/** Setter for tribunalResponsavel. */
	public void setTribunalResponsavel(TRF tribunalResponsavel) {
		this.tribunalResponsavel = tribunalResponsavel;
	}




		
		/** Getter for Source. */
		public  getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource( Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Source. */
		public Set<TurmaRecursal> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<TurmaRecursal> Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(SecaoJudiciaria o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}