package br.ufes.informatica.jurisproc.core.domain;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class TurmaRecursal extends PersistentObjectSupport implements Comparable<TurmaRecursal> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String competencia;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String acordao;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private SecaoJudiciaria Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Source")
		private Set<Relatoria> Target;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Target")
		private Set<Relatoria> Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private SecaoJudiciaria Target;
		
	




	/** Getter for competencia. */
	public String getCompetencia() {
		return competencia;
	}
	
	/** Setter for competencia. */
	public void setCompetencia(String competencia) {
		this.competencia = competencia;
	}

	/** Getter for acordao. */
	public String getAcordao() {
		return acordao;
	}
	
	/** Setter for acordao. */
	public void setAcordao(String acordao) {
		this.acordao = acordao;
	}




		
		/** Getter for Source. */
		public SecaoJudiciaria getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(SecaoJudiciaria Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Target. */
		public Set<Relatoria> getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Set<Relatoria> Target) {
			this.Target = Target;
		}
		
	

		
		/** Getter for Source. */
		public Set<Relatoria> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<Relatoria> Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Target. */
		public SecaoJudiciaria getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(SecaoJudiciaria Target) {
			this.Target = Target;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(TurmaRecursal o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}