package br.ufes.informatica.jurisproc.core.domain;

import java.util.Date;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Usuario extends PersistentObjectSupport implements Comparable<Usuario> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 100) 
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 100) 
	private String email;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 12) 
	private String senha;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@NotNull  @Temporal(TemporalType.TIMESTAMP)
	private Date dataRegistro;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 10) 
	private String OAB;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne
		private SystemRole Target;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Source")
		private Set<PedidoUniformizacao> Target;
		
	




	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for email. */
	public String getEmail() {
		return email;
	}
	
	/** Setter for email. */
	public void setEmail(String email) {
		this.email = email;
	}

	/** Getter for senha. */
	public String getSenha() {
		return senha;
	}
	
	/** Setter for senha. */
	public void setSenha(String senha) {
		this.senha = senha;
	}

	/** Getter for dataRegistro. */
	public Date getDataRegistro() {
		return dataRegistro;
	}
	
	/** Setter for dataRegistro. */
	public void setDataRegistro(Date dataRegistro) {
		this.dataRegistro = dataRegistro;
	}

	/** Getter for OAB. */
	public String getOAB() {
		return OAB;
	}
	
	/** Setter for OAB. */
	public void setOAB(String OAB) {
		this.OAB = OAB;
	}




		
		/** Getter for Target. */
		public SystemRole getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(SystemRole Target) {
			this.Target = Target;
		}
		
	

		
		/** Getter for Target. */
		public Set<PedidoUniformizacao> getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Set<PedidoUniformizacao> Target) {
			this.Target = Target;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Usuario o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}