package br.ufes.informatica.jurisproc.core.persistence;

import java.util.List;

import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.informatica.jurisproc.core.domain.PedidoUniformizacao;
import br.ufes.informatica.jurisproc.security.CurrentUser;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class PedidoUniformizacaoDAOJPA extends BaseJPADAO<PedidoUniformizacao> implements PedidoUniformizacaoDAO{
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
    @PersistenceContext
    private EntityManager entityManager;
    
    @Inject
    private CurrentUser currentUser;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	@Override
	public List<PedidoUniformizacao> buscaPorUsuario()
	{
		return entityManager.createQuery("FROM PedidoUniformizacao p WHERE p.usuario.id = :id_usu", PedidoUniformizacao.class).setParameter("id_usu", currentUser.getUsuario().getId()).getResultList();
	}
    
    

}