package br.ufes.informatica.jurisproc.core.persistence;

import javax.ejb.Stateful;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.informatica.jurisproc.core.domain.PedidoUniformizacao;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateful
public class PedidoUniformizacaoDAOJPA extends BaseJPADAO<PedidoUniformizacao> implements PedidoUniformizacaoDAO{
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
    @PersistenceContext(type = PersistenceContextType.EXTENDED)
    private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}
	
	@Override
	public PedidoUniformizacao buscaRegistroPorId(Long id)
	{
		return entityManager.find(PedidoUniformizacao.class, id);
	}
    
    

}