package br.ufes.informatica.jurisproc.core.persistence;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.jurisproc.core.domain.SecaoJudiciaria;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface SecaoJudiciariaDAO extends BaseDAO<SecaoJudiciaria> {
	
}