package br.ufes.informatica.jurisproc.core.persistence;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.informatica.jurisproc.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class UsuarioDAOJPA extends BaseJPADAO<Usuario> implements UsuarioDAO
{
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@PersistenceContext
	private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager()
	{
		return entityManager;
	}

	@Override
	public Usuario buscaPorEmail(String email)
	{
		return entityManager.createQuery("FROM Usuario u WHERE u.email = :em", Usuario.class).setParameter("em", email)
				.getResultList().stream().findFirst().orElse(null);
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Usuario buscaPorEmailESenha(String email, String senha)
	{
		return null;
	}

	@Override
	public void incluir(Usuario usuario)
	{
		entityManager.persist(usuario);		
	}

}