package br.ufes.informatica.jurisproc.core.controller;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import javax.servlet.http.Part;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.jurisproc.core.application.PedidoUniformizacaoService;
import br.ufes.informatica.jurisproc.core.domain.PedidoUniformizacao;

@Named
@RequestScoped
public class PedidoUniformizacaoController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	
	@EJB
	private PedidoUniformizacaoService pedidoUniformizacaoService;
	
	private Part anexoPedidoUniformizacao;
	private PedidoUniformizacao pedido = new PedidoUniformizacao();
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String cadastraPedidoUniformizacao() {
		System.out.println(pedido);
		return "core/peticao/index.xhtml?faces-redirect=true";
	}
	
	public String abreNovo()
	{
		return "core/peticao/form.xhtml?faces-redirect=true";
	}
	
	
	
	/** Getter for anexoPedidoUniformizacao. */
	public Part getAnexoPedidoUniformizacao() {
		return anexoPedidoUniformizacao;
	}

	/** Setter for anexoPedidoUniformizacao. */
	public void setAnexoPedidoUniformizacao(Part anexoPedidoUniformizacao) {
		this.anexoPedidoUniformizacao = anexoPedidoUniformizacao;
	}
	
	/** Getter for pedido. */
	public PedidoUniformizacao getPedido() {
		return pedido;
	}

	/** Setter for pedido. */
	public void setPedido(PedidoUniformizacao pedido) {
		this.pedido = pedido;
	}
	
}