package br.ufes.informatica.jurisproc.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;
import javax.servlet.http.Part;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.jurisproc.core.application.PedidoUniformizacaoService;
import br.ufes.informatica.jurisproc.core.domain.PedidoUniformizacao;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class PedidoUniformizacaoController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private PedidoUniformizacaoService pedidoUniformizacaoService;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Part anexoPedidoUniformizacao;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private PedidoUniformizacao pedido;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String cadastraPedidoUniformizacao() {
		// FIXME: auto-generated method stub
		return null;
	}
	
	
	
	/** Getter for anexoPedidoUniformizacao. */
	public Part getAnexoPedidoUniformizacao() {
		return anexoPedidoUniformizacao;
	}

	/** Setter for anexoPedidoUniformizacao. */
	public void setAnexoPedidoUniformizacao(Part anexoPedidoUniformizacao) {
		this.anexoPedidoUniformizacao = anexoPedidoUniformizacao;
	}
	
	/** Getter for pedido. */
	public PedidoUniformizacao getPedido() {
		return pedido;
	}

	/** Setter for pedido. */
	public void setPedido(PedidoUniformizacao pedido) {
		this.pedido = pedido;
	}
	
}