package br.ufes.informatica.jurisproc.core.controller;

import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.jurisproc.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class UsuarioController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Usuario usuario;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private String repeteSenha;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String registrar() {
		// FIXME: auto-generated method stub
		return null;
	}
	
	
	
	/** Getter for usuario. */
	public Usuario getUsuario() {
		return usuario;
	}

	/** Setter for usuario. */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	/** Getter for repeteSenha. */
	public String getRepeteSenha() {
		return repeteSenha;
	}

	/** Setter for repeteSenha. */
	public void setRepeteSenha(String repeteSenha) {
		this.repeteSenha = repeteSenha;
	}
	
}