package br.ufes.informatica.jurisproc.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.servlet.http.Part;

import br.ufes.informatica.jurisproc.core.domain.PedidoUniformizacao;
import br.ufes.informatica.jurisproc.core.persistence.AssuntoDAO;
import br.ufes.informatica.jurisproc.core.persistence.PedidoUniformizacaoDAO;
import br.ufes.informatica.jurisproc.core.persistence.SecaoJudiciariaDAO;
import br.ufes.informatica.jurisproc.infra.FileSaver;
import br.ufes.informatica.jurisproc.security.CurrentUser;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class PedidoUniformizacaoServiceBean implements PedidoUniformizacaoService
{
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private PedidoUniformizacaoDAO pedidoUniformizacaoDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private AssuntoDAO assuntoDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private SecaoJudiciariaDAO secaoJudiciariaDAO;

	@Inject
	private CurrentUser currentUser;
	
	@Inject
	private FileSaver fileSaver;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void cadastraPedidoUniformizacao(PedidoUniformizacao pedidoUniformizacao, Part part)
	{
		pedidoUniformizacao.setCaminhoPeticaoAnexo(fileSaver.write("peticoes", part));
		pedidoUniformizacao.setUsuario(currentUser.getUsuario());
		pedidoUniformizacaoDAO.save(pedidoUniformizacao);
	}

}