package br.ufes.informatica.jurisproc.core.application;

import java.io.Serializable;

import javax.ejb.Local;
import javax.servlet.http.Part;

import br.ufes.informatica.jurisproc.core.domain.PedidoUniformizacao;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface PedidoUniformizacaoService extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void cadastraPedidoUniformizacao(PedidoUniformizacao pedidoUniformizacao, Part part);
	
}