package br.ufes.informatica.jurisproc.core.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.informatica.jurisproc.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface UsuarioService extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public Boolean fazLogin(Usuario usuario);
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void enviaEmailParaRecuperacaoDeSenha(String email);
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void registrar(Usuario usuario);
	
}