package br.ufes.informatica.jurisproc.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.jurisproc.core.domain.Usuario;
import br.ufes.informatica.jurisproc.core.persistence.UsuarioDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class UsuarioServiceBean implements UsuarioService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private UsuarioDAO usuarioDAO;
	
	
	

	
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Boolean fazLogin(Usuario usuario) {
		// FIXME: auto-generated method stub
		return null;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void enviaEmailParaRecuperacaoDeSenha(String email) {
		// FIXME: auto-generated method stub
		return;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void registrar(Usuario usuario) {
		// FIXME: auto-generated method stub
		return;
	}
	
}